"""empty message

Revision ID: 18a0d08eea63
Revises: 
Create Date: 2018-05-23 11:24:28.689505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a0d08eea63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster',
    sa.Column('cluster_abbr_id', sa.INTEGER(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('left', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('cluster_abbr_id', 'cluster_id')
    )
    op.create_table('cluster_abbr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbr', sa.String(length=128), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('left', sa.INTEGER(), nullable=True),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_document',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('source_id', 'doc_id')
    )
    op.create_table('cluster_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.INTEGER(), nullable=True),
    sa.Column('doc_id', sa.INTEGER(), nullable=True),
    sa.Column('cluster_id', sa.INTEGER(), nullable=True),
    sa.Column('abbr_id', sa.INTEGER(), nullable=True),
    sa.Column('segement_position', sa.INTEGER(), nullable=True),
    sa.Column('fulltext_position', sa.INTEGER(), nullable=True),
    sa.Column('sense_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('abbr_id_cluster_id_index', 'cluster_instance', ['abbr_id', 'cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('abbr_id_cluster_id_index', table_name='cluster_instance')
    op.drop_table('cluster_instance')
    op.drop_table('cluster_document')
    op.drop_table('cluster_abbr')
    op.drop_table('cluster')
    # ### end Alembic commands ###
